# Generated by Django 3.2 on 2021-04-21 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='a',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
