# Generated by Django 3.2 on 2021-04-21 22:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_listing_a'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='a',
        ),
    ]
