# Generated by Django 3.2 on 2021-04-22 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_remove_listing_a'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='imageURL',
            new_name='image_URL',
        ),
        migrations.RenameField(
            model_name='listing',
            old_name='startingBid',
            new_name='starting_bid',
        ),
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.CharField(help_text='Again, not required, but this could help your product gain the spotlight it deserves! Examples of categories include Fashion, Toys, Electronics, Home, etc.', max_length=64),
        ),
    ]
