# Generated by Django 3.2 on 2021-04-25 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_bids'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bids',
            name='value_offer',
            field=models.DecimalField(decimal_places=2, help_text='How much are you willing to pay for this item?', max_digits=6),
        ),
    ]
